sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yhf20001116
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7oBmabpDba3n3CMvMU
    access-key-secret: p3PezOklaZapuL7v1PiWRwl1A6DmG3
    bucket-name: sky-project-yhf