sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yhf20001116
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7oBmabpDba3n3CMvMU
    access-key-secret: p3PezOklaZapuL7v1PiWRwl1A6DmG3
    bucket-name: sky-project-yhf

  redis:
    host: localhost
    port: 6379
    password: yhf20001116
    database: 10

  wechat:
    appid: wxad388af06e266467
    secret: 8cadab5a1e077b953272df7afdb392f4